-- MySQL Script generated by MySQL Workbench
-- Tue May  5 17:33:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idLivro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `isbn` BIGINT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `imagem` LONGBLOB ,
  PRIMARY KEY (`idLivro`),
  UNIQUE INDEX `id_livro_UNIQUE` (`idLivro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `num` INT NOT NULL,
  `comp` VARCHAR(100),
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEndereco` INT UNSIGNED ,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `cpf` INT,
  `fone` INT ,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `fone_UNIQUE` (`fone` ASC) VISIBLE,
  INDEX `fk_usuario_Endereco1_idx` (`idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `idPagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metodo` VARCHAR(15) NOT NULL,
  `nomeTitular` VARCHAR(45) NULL,
  `cpfTitular` INT NULL,
  `numCartao` INT NULL,
  `codSeguranca` INT NULL,
  `validade` INT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `idCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsuario` INT UNSIGNED NOT NULL,
  `idPagamento` INT UNSIGNED NOT NULL,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idCompra`),
  UNIQUE INDEX `id_venda_UNIQUE` (`idCompra` ASC) VISIBLE,
  INDEX `fk_compra_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_compra_pagamento1_idx` (`idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_pagamento1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `mydb`.`pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `idAvaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `avaliado` INT UNSIGNED NOT NULL,
  `avaliador` INT UNSIGNED NOT NULL,
  `nota` INT NOT NULL,
  `comentario` VARCHAR(1000) NULL,
  PRIMARY KEY (`idAvaliacao`),
  UNIQUE INDEX `id_avaliacao_UNIQUE` (`idAvaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_usuario1_idx` (`avaliado` ASC) VISIBLE,
  INDEX `fk_avaliacao_usuario2_idx` (`avaliador` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`avaliado`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario2`
    FOREIGN KEY (`avaliador`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idGenero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `id_genero_UNIQUE` (`idGenero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idVenda` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL,
  `idLivro` INT UNSIGNED NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_venda_livro1_idx` (`idLivro` ASC) VISIBLE,
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_livro1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `mydb`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro_has_genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro_has_genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro_has_genero` (
  `idLivro` INT UNSIGNED NOT NULL,
  `idGenero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLivro`, `idGenero`),
  INDEX `fk_livro_has_genero_genero1_idx` (`idGenero` ASC) VISIBLE,
  INDEX `fk_livro_has_genero_livro1_idx` (`idLivro` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_genero_livro1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `mydb`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_genero_genero1`
    FOREIGN KEY (`idGenero`)
    REFERENCES `mydb`.`genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalhe_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalhe_compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalhe_compra` (
  `idDetalhe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLivro` INT UNSIGNED NOT NULL,
  `idCompra` INT UNSIGNED NOT NULL,
  `valor_compra` DOUBLE NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDetalhe`, `idLivro`, `idCompra`),
  UNIQUE INDEX `iddetalhe_compra_UNIQUE` (`idDetalhe` ASC) VISIBLE,
  INDEX `fk_detalhe_compra_livro1_idx` (`idLivro` ASC) VISIBLE,
  INDEX `fk_detalhe_compra_compra1_idx` (`idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_detalhe_compra_livro1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `mydb`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhe_compra_compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `mydb`.`compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from mydb.avaliacao;
select * from mydb.compra;
select * from mydb.endereco;
select * from mydb.genero;
select * from mydb.livro;
select * from mydb.pagamento;
select * from mydb.usuario;
select * from mydb.venda;
select * from mydb.detalhe_compra;
select * from mydb.livro_has_genero;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
