-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 18:25:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoPI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetoPI` ;

-- -----------------------------------------------------
-- Schema projetoPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoPI` DEFAULT CHARACTER SET utf8 ;
USE `projetoPI` ;

-- -----------------------------------------------------
-- Table `projetoPI`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`usuario` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `cpf` INT,
  `fone` INT,
  `endereco_id_endereco` INT unsigned,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `fone_UNIQUE` (`fone` ASC) ,
  INDEX `fk_usuario_endereco1_idx` (`endereco_id_endereco` ASC) ,
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `projetoPI`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projetoPI`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`endereco` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`endereco` (
  `id_endereco` INT UNSIGNED AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `num` INT NOT NULL,
  `cep` INT NOT NULL,
  `comp` VARCHAR(100),
  PRIMARY KEY (`id_endereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`id_endereco` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projetoPI`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`livro` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`livro` (
  `id_livro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `isbn` BIGINT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `imagem` LONGBLOB NOT NULL,
  `compra_id_compra` INT unsigned,
  `venda_id_venda` INT unsigned NOT NULL ,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `id_livro_UNIQUE` (`id_livro` ASC) ,
  UNIQUE INDEX `ISBN_UNIQUE` (`isbn` ASC) ,
  INDEX `fk_livro_compra1_idx` (`compra_id_compra` ASC) ,
  INDEX `fk_livro_venda1_idx` (`venda_id_venda` ASC) ,
  CONSTRAINT `fk_livro_compra1`
    FOREIGN KEY (`compra_id_compra`)
    REFERENCES `projetoPI`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projetoPI`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projetoPI`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`compra` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`compra` (
  `id_compra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `metodo_pgto` VARCHAR(45) NOT NULL,
  `qtd` INT NOT NULL,
  `usuario_id_usuario` INT unsigned NOT NULL,
  PRIMARY KEY (`id_compra`),
  UNIQUE INDEX `id_venda_UNIQUE` (`id_compra` ASC) ,
  INDEX `fk_compra_usuario1_idx` (`usuario_id_usuario` ASC) ,
  CONSTRAINT `fk_compra_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`venda` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`venda` (
  `id_venda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT unsigned NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_usuario1_idx` (`usuario_id_usuario` ASC) ,
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projetoPI`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`avaliacao` (
  `id_avaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nota` INT NOT NULL,
  `comentario` VARCHAR(1000) NULL,
  `avaliado` INT unsigned NOT NULL,
  `avaliador` INT unsigned NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  UNIQUE INDEX `id_avaliacao_UNIQUE` (`id_avaliacao` ASC) ,
  INDEX `fk_avaliacao_usuario1_idx` (`avaliado` ASC) ,
  INDEX `fk_avaliacao_usuario2_idx` (`avaliador` ASC) ,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`avaliado`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario2s`
    FOREIGN KEY (`avaliador`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`genero` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`genero` (
  `id_genero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id_genero` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`livro_has_genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoPI`.`livro_has_genero` ;

CREATE TABLE IF NOT EXISTS `projetoPI`.`livro_has_genero` (
  `livro_id_livro` INT unsigned NOT NULL,
  `genero_id_genero` INT unsigned NOT NULL,
  PRIMARY KEY (`livro_id_livro`, `genero_id_genero`),
  INDEX `fk_livro_has_genero_genero1_idx` (`genero_id_genero` ASC) ,
  INDEX `fk_livro_has_genero_livro1_idx` (`livro_id_livro` ASC) ,
  CONSTRAINT `fk_livro_has_genero_livro1`
    FOREIGN KEY (`livro_id_livro`)
    REFERENCES `projetoPI`.`livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_genero_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `projetoPI`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SELECT * FROM endereco;
SELECT * FROM usuario;
SELECT * FROM compra;
SELECT * FROM venda;
SELECT * FROM livro;
SELECT * FROM avaliacao;
SELECT * FROM genero;
SELECT * FROM livro_has_genero;

insert into genero(tipo) VALUES 
('Biografia'),
('Ficção'),
('Infantil'),
('Romance'),
('Terror');

insert into livro(isbn,titulo,autor,editora,preco,descricao,imagem,venda_id_venda) VALUES 
(9788525056009,'titulo','Aldous Huxley','Biblioteca azul',12.00,'A terra agora se divide em...',LOAD_FILE('C:\Users\acer\Desktop\Livros\admirável.jpg'),1);





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
